# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicants',
            old_name='currenmt_employer',
            new_name='current_employer',
        ),
    ]
