# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_auto_20160613_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
