# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_auto_20160613_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='user',
        ),
    ]
